- cmd/main.go
- cmd/main_test.go
- docs/argocd-notifications-secret.yaml
- Divide the parse part of notifier.yaml into functions
- Add testcase to parse notifier.yaml
- Fixed indent of sample docs/argocd-notifications-secret.yaml 
- In the future, I think that it is better to parse the yaml into another module, but I think it is not at that time yet, so I added only the test.
> Add testcase to parse notifier.yaml

- cmd/main_test.go
- docs/argocd-notifications-secret.yaml
- notifiers/slack.go
- If slack username is specified in notifer.yaml, the username set in token is overwritten with the specified username
> feat: override notification slack username

- testing/testing.go
- triggers/expr/expr.go
- triggers/expr/expr_test.go
- triggers/expr/time.go
- triggers/expr/time_test.go
- triggers/triggers.go
- triggers/triggers_test.go
Provide `expr.Env` while evaluating trigger condition. At this time, only 2 functions are provided.
- `toTime(t string)` : parse t as RFC3339, return `time.Time`
- `now()` : return current time as `time.Time`
with this feature, we can notify long-running operations.
close #17
> Provide expr.Env while evaluating trigger condition

- docs/argocd-notifications-secret.yaml
- notifiers/slack.go
- notifiers/slack_test.go
Allows to define an 'icon' field in Slack notifier options. It has very simple validation to check if it is emoij notation or url notation and sets the Slack msg options accordingly.
fixes #47
> feat: Add icon emoij and icon url support for Slack messages (fixes #47)

- docs/recipients/overview.md
- docs/services/grafana.md
- notifiers/grafana.go
- notifiers/notifiers.go
- shared/settings/settings_test.go
Hi all,
Here is a PR to create a notifier for Grafana in order to create an annotation with specific tags.
In order to configure this notifier we have to configure the `notifiers.yaml` like that:
```
apiVersion: v1
kind: Secret
metadata:
name: argocd-notifications-secret
stringData:
notifiers.yaml: |
grafana:
apiUrl: https://grafana.example.com/api
apiKey: <grafana-api-key> 
```
And the recipient has to be configured like that:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
annotations:
recipients.argocd-notifications.argoproj.io: grafana:tag1|tag2
```
I chose `|` as separator for the tags cause `,` is already used for the notifiers.
Nicolas
> Grafana annotation notifier

- docs/recipients/overview.md
just added a note about how to define multiple recipients using annotations (https://github.com/argoproj-labs/argocd-notifications/blob/master/shared/recipients/annotations.go#L41)
> docs: multiple recipients example

- docs/argocd-notifications-cm.yaml
If you use the doc as-is you get:
```console
level=fatal msg="Failed to parse new settings: error unmarshaling JSON: json: cannot unmarshal string into Go struct field Config.subscriptions of type []string"
```
> fix(doc): recipients are []string

- CHANGELOG.md
- builtin/templates.go
- builtin/templates_test.go
- notifiers/slack.go
- testing/testing.go
Closes #65 
PR updates built-in templates so that generated slack attachement is valid json object definition.
> fix: ensure slack attachment properly formatted json object

- cmd/controller.go
- notifiers/notifiers.go
- shared/settings/settings.go
- shared/settings/settings_test.go
> fix: use strategic merge patch to merge built-in and user provided config

- notifiers/webhook.go
- notifiers/webook_test.go
> fix: don't append slash to webhook url (#70)

- docs/index.md
This PR is meant to facilitate others migrating to using Helm for installing and managing argocd-notifications based on the work done in [argoproj/argo-helm](https://github.com/argoproj/argo-helm/tree/master/charts/argocd-notifications).  However, I kept the original getting started instructions until the project decides to solely support Helm installation or not.
Any feedback is welcome especially as helm/monocular doesn't support displaying Helm v3 instructions yet: https://github.com/helm/monocular/pull/660
> Adding Helm v3 getting started notes

- Dockerfile
- manifests/controller/argocd-notifications-controller-deployment.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
We don't need to specify `runAsUser` because the USER in the Dockerfile is the numeric user 1000 and kubernetes will be able to assert that the USER isn't root (0).
When you use a non-numeric USER in the Dockerfile, you need to specify `runAsUser` because kubernetes can't make sure that the specified user isn't root just by inspecting the docker image.
But using `runAsUser` isn't desirable because it complicates things, in our case we have a mix of kops(in aws) and openshift clusters and for openshift it injects the `runAsUser` automatically and if it's not in the random range assigned to the namespace, it fails, and the random range for user ids is usually very high (> 1000000000).
> Run kubernetes deployment as non-root

- controller/controller.go
- controller/controller_test.go
- shared/recipients/annotations.go
- shared/recipients/annotations_test.go
This will fix #79 bug.
* I does have breaking changes.
The fact that notification was sent previously was stored on the application annotation as: `TRIGGER_NAME.argocd-notifications.argoproj.io: "time.Now()"`. Now, in order to stop resending to successful recipients, it will store trigger + recipient as `TRIGGER_NAME.NORMALIZED_RECIPIENT.argocd-notifications.argoproj.io: "time.Now()"`. Where normalized recipient is just replacement of `:` to `.` to follow kubernetes annotations regexp validation.
> feat: do not resend successful notification fix #79

- bot/slack/slack.go
- bot/slack/verify.go
- go.mod
- go.sum
- notifiers/slack.go
The slack library has moved from github.com/nlopes/slack to github.com/slack-go/slack. The former may no longer receive updates, and urges users to update their imports.
closes #120
> change nlopes/slack imports to slack-go/slack

- controller/controller.go
- controller/controller_test.go
- shared/recipients/annotations_test.go
fixes: #117
Here is the new format:
```
metadata:
annotations:
on-sync-succeeded.argocd-notifications.argoproj.io: |
slack:general=2020-11-23T17:31:32-08:00
```
> fix annotations for tracking notifications have sent.

- builtin/templates/app-health-degraded.yaml
- builtin/templates/app-sync-failed.yaml
- builtin/templates/app-sync-running.yaml
- builtin/templates/app-sync-status-unknown.yaml
- builtin/templates/app-sync-succeeded.yaml
- manifests/controller/argocd-notifications-cm.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
fixes #126 
After the fix, slack messages is received when there are multiple elements in `app.status.conditions`
> fix: Argo notifications fails to send notification with "invalid character

- docs/templates.md
- pkg/api.go
- pkg/api_test.go
> feat: templates have access to 'recipient' via context variable

- pkg/triggers/service.go
- pkg/triggers/service_test.go
PR fixes the trigger `oncePer` field value extraction
Closes https://github.com/argoproj-labs/argocd-notifications/issues/153
> fix: the on-deployed trigger sends multiple notifications

- catalog/triggers/on-deployed.yaml
This revision changes only if someone run sync operation or manifest changes are detected.
#156
> feat: oncePeer - Trigger messages only when manifest changes (#156)

- docs/services/slack.md
Based on https://argocd-notifications.readthedocs.io/en/stable/services/overview/#sensitive-data
I believe the example secret is using the wrong key
> Fix slack example secret

- catalog/install.yaml
Colourise the sync running notification the same as in the gui client, so #F4C030 when it's out of sync
> Colourise sync running based on current status

- docs/templates.md
- shared/settings/settings.go
Extending the documentation on defining `context` for templates. In reading the source code to understand how to use it, I found it could be easier to follow by checking for the specific keys rather than iterating, and unmarshaling the inner YAML directly into the target struct.
> Add documentation to configuring template Context, clarify source code.

- docs/assets/versions.css
- docs/assets/versions.js
- mkdocs.yml
This PR would add versioning capability through READTHEDOCS service. URLs should already be working for bringing it into https://readthedocs.org/projects/argocd-notifications/.
> feat: add versioning to docs

- .github/workflows/ci.yaml
- Dockerfile
- Makefile
This PR focuses on creating multiarch images by default (currently `linux/amd64`,`linux/arm64` and `linux/arm`) this can be easily extended to others).
I have only added pushing to `docker.pkg.github.com` as that was what existed in the existing `ci.yaml` file, but it can be trivially extended on request to also push to DockerHub automatically as part of the workflow (would require a username and password secret to be added to the repo for DockerHub).
As it stands, this PR uses Docker Buildx and Qemu to build a common builder image (based on the arch of the platform it is building on) and then creates layers for each target OS and target arch [specified here](https://github.com/argoproj-labs/argocd-notifications/compare/master...mylesagray:master#diff-944291df2c9c06359d37cc8833d182d705c9e8 …
> feat: Added multiarch builds using GitHub workflows and buildx

- docs/services/github.md
- docs/services/overview.md
- expr/repo/repo.go
- expr/repo/repo_test.go
- go.mod
- go.sum
- mkdocs.yml
- pkg/config.go
- pkg/config_test.go
- pkg/services/github.go
- pkg/services/github_test.go
- pkg/services/services.go
> feat: GitHub App integration

- .github/workflows/ci.yaml
Per comments in #184 I have migrated the CI workflow from the deprecated GitHub Packages to the new GitHub Container Registry.
Note that images will be tagged the same way they are today - and an additional `:latest` tag will be added to each push as well.
This PR will need a few things done before it is merged:
- Two secrets need to be created on the GH repo:
- GH_USERNAME - a user with ownership over the argoproj-labs GH Org
- GH_PAT - a personal access token with `package:read`, `package:write` and `package:delete` permissions. more here: <https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry>
Once those pre-reqs are met this is safe to merge and should auto build and push fresh multi-arch images …
> Migrated from deprecated to GitHub Packages to GHCR

- manifests/controller/argocd-notifications-controller-role.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
> feat: add role resourceNames

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
As per discussion in #190  - this adds support for automatic releases to DockerHub and GHCR.
This workflow can only be invoked via the "Run workflow" in the GitHub Actions UI.
It will publish images with tags reflecting what is in `Makefile` - the output of "v" + `VERSION` file and will tag whatever image that is with the `latest` tag as well.
I have noted on DockerHub that the image tags are of format `v1.0.0` and this PR reflects that - would we rather a different tagging scheme or is this okay? /cc @alexmt for 👀
> Feat: Automated release to GitHub and GHCR

- docs/services/mattermost.md
- docs/services/overview.md
- docs/services/slack.md
- pkg/services/mattermost.go
- pkg/services/mattermost_test.go
- pkg/services/services.go
refs: #176
I don't use [mattermost/mattermost-server model/client4.go](https://github.com/mattermost/mattermost-server/blob/master/model/client4.go), because it is too large to use library.
> support mattermost integration

- mkdocs.yml
> docs: fix missing mattermost nav

- docs/argocd-notifications-cm.yaml
- docs/triggers.md
Signed-off-by: toVersus <toversus2357@gmail.com>
When I tried to add default triggers following the instruction described in docs (#221), I got an error:
```bash
$ cat <<EOF > argocd-notifications-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: argocd-notifications-cm
data:
defaultTriggers:
- on-sync-status-unknown
EOF
$ kubectl diff -n default -f argocd-notifications-cm.yaml
Error from server (BadRequest): ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found [, error found in #10 byte of ...|riggers":["on-sync-s|..., bigger context ...|{"apiVersion":"v1","data":{"defaultTriggers":["on-sync-status-unknown"]},"kind":"ConfigMap","met|...
```
With this fix, a ConfigMap can be created without any errors and it works as …
> Fix yaml syntax for defaultTriggers in ConfigMap

- docs/index.md
Update the Getting Started documentation to use the v1.1.0 install manifests, as opposed to the old v1.0.2 manifests.
> Update install manifests to v1.1.0

- mkdocs.yml
> docs: teams nav is missing

- cmd/tools/template.go
> fix: call repo function failed for cli

- manifests/controller/argocd-notifications-controller-role.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
allow the argocd-notifications-controller to list and watch configmaps and secrets, so it can refresh stale resources being watched
(noticed it is still throwing warnings without the namespace wide watch permission)
I believe this still honors the original issue by only allowing get permissions on the argocd-notifications-controller owned configmap and secret, instead of all configmaps and secrets in the same namespace.
fixes #237
> allow configmap/secret list verb

- catalog/install.yaml
- catalog/templates/app-deployed.yaml
- catalog/templates/app-health-degraded.yaml
- catalog/templates/app-sync-failed.yaml
- catalog/templates/app-sync-succeeded.yaml
- docs/catalog.md
- docs/services/teams.md
- pkg/services/teams.go
- pkg/services/teams_test.go
Teams also have theme color field for the message card, suggest for enabling templating it as Slack template supported.
Template example:
```yaml
template.app-sync-succeeded: |
teams:
themeColor: '#000080'
```
> feat. support teams theme color templating

- catalog/install.yaml
- catalog/templates/app-deployed.yaml
- catalog/templates/app-health-degraded.yaml
- catalog/templates/app-sync-failed.yaml
- catalog/templates/app-sync-running.yaml
- catalog/templates/app-sync-status-unknown.yaml
- catalog/templates/app-sync-succeeded.yaml
- docs/catalog.md
There was a trailing comma at the end of the condition fact value
which made the JSON syntactically invalid causing notifications
to not be handled / published.
> Fix syntax error in Teams notifications

- controller/controller.go
- controller/controller_test.go
- go.mod
- go.sum
> refactor: upgrade notifications-engine and switch to WithAlterDestinations

- cmd/controller.go
- shared/k8s/informers.go
> feat: support dynamic ConfigMap name and Secret name

- mkdocs.yml
Since Rocketchat documentation was finished by @alexmt. I guess we can add it into documentation website on master branch. If it's not released currently
> docs: Add RocketChat page to documentation

- docs/requirements.txt
refs: https://github.com/argoproj/argo-cd/pull/6421
> chore: pin mkdocs version to fix docs build

- docs/triggers.md
To make the sentence clearer
- add "," after "however"
- "might unnecessary generate" -> "might unnecessarily generate"
> docs: fix tiny English mistakes

- docs/functions.md
- expr/expr.go
- expr/sync/sync.go
- expr/sync/sync_test.go
PR adds `sync.GetInfoItem` that simplifies retrieving operation info items by name
> feat: add sync.GetInfoItem function
