argoproj-labs/argocd-notifications

- CHANGELOG.md
- controller/controller.go
- controller/controller_test.go
- docs/recipients.md
- testing/testing.go
> feat: Trigger specific subscriptions

- docs/argocd-notifications-secret.yaml
- go.mod
- go.sum
- notifiers/notifiers.go
- notifiers/opsgenie.go
Hi!
This PR adds support for notifying [Opsgenie](https://www.atlassian.com/software/opsgenie). The changes are pretty simple, so just let me know what you think.
Best,
Dominik
> feat: add opsgenie support

- cmd/main.go
- cmd/main_test.go
- triggers/triggers.go
- Added unittest for parsing config.yaml
- Fix parse failure in templates section.
> Add config.yaml parse unit test

- triggers/triggers_test.go
- Added test case using slack in GetTriggers
- Added test case using context in GetTriggers
> Added testcase GetTriggers 

- docs/argocd-notifications-secret.yaml
- docs/recipients.md
- docs/services/opsgenie.md
- docs/services/overview.md
- docs/services/slack.md
- docs/triggers_and_templates/index.md
- mkdocs.yml
> docs: document slack app creation

- cmd/main.go
- cmd/main_test.go
> fix: fix null pointer dereference error while config parsing

- bot/server.go
- shared/recipients/annotations_test.go
makes codecov a little happier
> add missing recipients package tests

- cmd/controller.go
Controller prints warning if secret of config map is missing:
```
WARN[0011] Cannot find config map argocd-notifications-cm and secret argocd-notifications-secret. Waiting when both config map and secret are created. 
```
> warn if config map of secret is missing

- bot/server.go
- bot/slack/slack.go
- bot/slack/slack_test.go
- bot/slack/verify.go
- bot/slack/verify_test.go
- cmd/bot.go
- cmd/controller.go
- cmd/controller_test.go
- notifiers/slack.go
- shared/settings/informers.go
- shared/settings/settings.go
- shared/settings/settings_test.go
> implement slack signature verification

- builtin/templates.go
- cmd/controller.go
- docs/argocd-notifications-cm.yaml
- docs/services/grafana.md
- docs/services/webhook.md
- docs/triggers_and_templates/index.md
- go.mod
- go.sum
- manifests/install-bot.yaml
- mkdocs.yml
- notifiers/notifiers.go
- notifiers/slack.go
- notifiers/webhook.go
- notifiers/webook_test.go
- shared/settings/settings.go
- shared/settings/settings_test.go
- shared/text/strings.go
- triggers/expr/expr.go
- triggers/expr/expr_test.go
- triggers/expr/repo/repo.go
- triggers/expr/repo/repo_test.go
- triggers/expr/time/time.go
- triggers/expr/time/time_test.go
- triggers/triggers.go
- triggers/triggers_test.go
> feat: support sending the generic webhook request

- cmd/controller.go
- controller/controller.go
- controller/controller_test.go
- testing/testing.go
rough idea for Slack topic https://argoproj.slack.com/archives/CSPC6G5JQ/p1582708685014500
> Wait for next reconciliation after sync

- docs/services/grafana.md
@nhuray, do you mind if I use your screenshot in grafana documentation?
> docs: add screenshot to grafana docs

- CHANGELOG.md
- cmd/controller.go
- cmd/controller_test.go
- controller/controller.go
- controller/controller_test.go
- docs/argocd-notifications-cm.yaml
- docs/recipients/overview.md
- shared/recipients/annotations.go
- shared/settings/settings.go
- shared/settings/settings_test.go
> feat: support default subscriptions

- docs/services/slack.md
> docs: describe required scope for username and icon overrides

- docs/triggers_and_templates/index.md
> document 'notificationType' field

- docs/argocd-notifications-cm.yaml
- docs/index.md
Documentation- How to set argocdUrl & set annotation to an argo project.
> Documentation- How to set argocdUrl & set annotation to an argo project. 

- controller/controller.go
- controller/controller_test.go
PR fixes bug because of which notification is not sent due to stale data in informer cache. To reproduce:
- create app with 1 config map so that sync happens very quickly.
- make sure `on-sync-succeeded` is configured.
- sync app - notification is sent
- sync app again - notification is not sent because controller mistakenly thinks that notification was sent already.
> fix: notification is not sent due to stale application data in informer

- cmd/main.go
- cmd/tools/context.go
- manifests/controller/argocd-notifications-controller-deployment.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
- notifiers/grafana.go
- notifiers/opsgenie.go
- notifiers/slack.go
- notifiers/webhook.go
- shared/http/transport.go
> fix: Support self-signed certificates and HTTP proxy settings

- bot/slack/verify.go
- docs/argocd-notifications-cm.yaml
- docs/argocd-notifications-secret.yaml
- docs/services/grafana.md
- docs/services/opsgenie.md
- docs/services/slack.md
- notifiers/notifiers.go
- notifiers/slack.go
- notifiers/webhook.go
- shared/settings/legacy.go
- shared/settings/legacy_test.go
- shared/settings/settings.go
- shared/settings/settings_test.go
- triggers/triggers.go
Closes https://github.com/argoproj-labs/argocd-notifications/issues/76
> feat: split notifiers.yaml into multiple keys; support registering more than one slack/email etc

- cmd/controller.go
Closes https://github.com/argoproj-labs/argocd-notifications/issues/123
```
-> % go run cmd/main.go cmd/controller.go cmd/bot.go controller --logformat=text
INFO[0000] serving metrics on port 9001
INFO[0000] loading configuration 9001
INFO[0000] config map found
INFO[0000] secret found
...
-> % go run cmd/main.go cmd/controller.go cmd/bot.go controller --logformat=json
{"level":"info","msg":"serving metrics on port 9001","time":"2021-01-09T18:52:24+09:00"}
{"level":"info","msg":"loading configuration 9001","time":"2021-01-09T18:52:24+09:00"}
{"level":"info","msg":"secret found","time":"2021-01-09T18:52:24+09:00"}
{"level":"info","msg":"config map found","time":"2021-01-09T18:52:24+09:00"}
...
-> % go run cmd/main.go cmd/controller.go cmd/bot.go controller --logformat=ltsv
Error: Unknown …
```
> feat: add --logformat flag to configure log output format

- Dockerfile
- Makefile
- cmd/bot.go
- cmd/controller.go
- cmd/main.go
- cmd/tools/context.go
- cmd/tools/template.go
- cmd/tools/tools.go
- cmd/tools/trigger.go
- cmd/tools/trigger_test.go
- docs/subscriptions.md
- docs/troubleshooting-commands.md
- docs/troubleshooting.md
- go.mod
- manifests/bot/argocd-notifications-bot-deployment.yaml
- manifests/controller/argocd-notifications-controller-deployment.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
> feat: argocd-notifications should be published with release

- docs/services/webhook.md
Hi ! I suggest a little fix for the documentation because I wasted quite time to solve my issue when trying to implement my custom webhook with v1.0.0-rc1.
> fix: documentation for webhook implementation

- pkg/subscriptions/annotations.go
- pkg/subscriptions/annotations_test.go
> improve annotation iterate

- docs/services/email.md
> docs: add email sample without authentication

- catalog/install.yaml
- catalog/templates/app-deployed.yaml
- catalog/templates/app-health-degraded.yaml
- catalog/templates/app-sync-failed.yaml
- catalog/templates/app-sync-running.yaml
- catalog/templates/app-sync-status-unknown.yaml
- catalog/templates/app-sync-succeeded.yaml
- docs/catalog.md
- docs/services/overview.md
- docs/services/teams.md
- pkg/services/services.go
- pkg/services/teams.go
- pkg/services/teams_test.go
Teams integration
related to #111
> feat: teams notification service

- cmd/main.go
- pkg/util/http/transport.go
> refactor: remove Argo CD depenency from 'pkg' package

- docs/services/telegram.md
Related to https://github.com/argoproj-labs/argocd-notifications/issues/196
> Improving doc on Telegram on my issue.

- docs/services/slack.md
https://github.com/argoproj-labs/argocd-notifications/issues/196
> Update Slack doc adding missing steps to solve my issue.

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> chore: automatically push commit specific images to ghcr.io/argoproj-labs/argocd-notifications

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
refs: #33 
https://github.com/codecov/codecov-action/issues/29#issuecomment-594958141
> chore: codecov supports tokenless upload

- docs/services/telegram.md
- pkg/services/telegram.go
> feat: support telegram private channel

- controller/controller.go
> fix: missing argocd_notifications_trigger_eval_total

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- go.sum
- pkg/mocks/mocks.go
- pkg/services/mocks/mocks.go
- shared/argocd/mocks/service.go
> chore: validate 'make generate' produce no differences

- go.mod
- go.sum
```
$ go mod edit -go=1.16
$ go mod tidy
```
> fix: fix go.mod

- docs/services/grafana.md
> docs: improve grafana docs

- docs/services/webhook.md
Signed-off-by: Ryota Sakamoto sakamo.ryota+github@gmail.com
refs: #134
> docs: add form-data example using webhook

- docs/triggers.md
> docs: add defaultTriggers description

- docs/templates.md
- pkg/services/services.go
- pkg/services/slack_test.go
> feat: support change timezone

- docs/index.md
> Add Getting Started for Kustomize

- docs/triggers.md
- pkg/triggers/service.go
- pkg/triggers/service_test.go
> feat: improve oncePer evaluate

- catalog/install.yaml
- catalog/templates/app-created.yaml
- catalog/templates/app-deleted.yaml
- catalog/triggers/on-created.yaml
- catalog/triggers/on-deleted.yaml
- docs/catalog.md
Closes https://github.com/argoproj-labs/argocd-notifications/issues/125
> feat: ArgoCD Notifications for Created, Deleted status

- CHANGELOG.md
> docs: add v1.1 changelog

- docs/assets/versions.css
- docs/assets/versions.js
same: https://github.com/argoproj/argo-cd/pull/5649
> fix: docs version selector not rendering

- docs/services/teams.md
> docs: improve teams docs

- docs/index.md
Update the command example to download YAML instead of HTML using raw.githubusercontent.com.
> docs: Update Kustomize Getting Started

- go.mod
- go.sum
- pkg/services/slack.go
Fixes #211 
Rather than returning RateLimitedError back up to the controller, actually handle it and retry.
> Handle slack RateLimitedError when posting messages

- controller/controller.go
- docs/triggers.md
- pkg/config.go
- pkg/config_test.go
- pkg/controller/subscriptions.go
- pkg/controller/subscriptions_test.go
- shared/legacy/subscriptions.go
- shared/legacy/subscriptions_test.go
Signed-off-by: Ryota Sakamoto sakamo.ryota+github@gmail.com
refs: #202
> feat: support defaultTriggers.<service>

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement_proposal.md
> chore: add ISSUE_TEMPLATE

- docs/index.md
- docs/triggers.md
> docs: improve kustomization getting started guide

- .github/ISSUE_TEMPLATE/config.yml
> docs: add 'New service integration request' to new issue template

- shared/argocd/service.go
> fix: fix nil pointer dereferece in repo.GetAppDetails function

- manifests/controller/argocd-notifications-controller-deployment.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
Solves https://github.com/argoproj-labs/argocd-notifications/issues/272.
I added the tcpSocket livenessProbe to the metrics port.
> Add livenessProbe to controller

- docs/services/slack.md
- docs/services/teams.md
- go.mod
- go.sum
refs: #263 
diff: https://github.com/argoproj/notifications-engine/compare/9766113a8ad7...ddadc858f038
> chore: update notifications-engine

- controller/controller.go
- go.mod
- go.sum
> refactor: upgrade notifications-engine version

- cmd/controller.go
- cmd/tools/tools.go
- docs/troubleshooting-commands.md
- manifests/controller/argocd-notifications-controller-deployment.yaml
- manifests/install-bot.yaml
- manifests/install.yaml
- shared/argocd/service.go
> feat: support plaintext connection to repo-server

- cmd/bot.go
- docs/bots/overview.md
> feat: Add configuration argument for slack bot handler

- docs/troubleshooting-errors.md
- docs/troubleshooting.md
> docs: add troubleshooting errors

- docs/index.md
> docs: add helm sample

- controller/controller.go
> fix: use namespace informer #322

- docs/subscriptions.md
> docs: add description for using webhook in subscriptions

- go.mod
- go.sum
Include https://github.com/argoproj/notifications-engine/issues/53
> feat: update version with telegram changes

- catalog/install.yaml
- catalog/templates/app-health-degraded.yaml
- docs/catalog.md
- go.mod
- go.sum
It should check app.status.health.status
Signed-off-by: Shyukri Shyukriev <shyukri.shyukriev@mariadb.com>
> Fix Health Degraded template

- docs/functions.md
- expr/strings/strings.go
- expr/strings/strings_test.go
* Support `ToUpper` and `ToLower` function with `strings` expression.
* Add more tests.
> feat: strings exprs support ToUpper and ToLower function

- README.md
The repo admin should also mark the repo as "inactive" in Github settings
> docs: Make it clear that this repo is inactive
